### ISSUE TITLE
Логотип не меняется в Neat

### ISSUE THREAD

**Issue by yura11212** [vertexofvortex/minecorpmod#2]
_Значит я как лучший тестер начинаю писать issues также ты сказал что сюда можно писать пожелания такчто я буду писать 1 пожелание в одну тему_

Вообщем ставим тему Neat и вот мне не нравится этот белый логотип я хочу другой поставить, выбираю например "Классический" логотип и он просто не меняется! 

Вобщем вертекс, если ты не писюн исправь этот баг и добавь чтоб логотип не был белый полностью а типо чтоб черно белый.!
![cY4AamHWOg](https://user-images.githubusercontent.com/60667108/73774673-14042c00-478d-11ea-85e1-ae76b70024ef.gif)

**Comment by vertexofvortex** [comment]
Не меняется, потому что изменение логотипа в теме не может быть перекрыто опцией пользовательского логотипа.
