### ISSUE TITLE
Новый баг с кнопками (Может не баг)

### ISSUE THREAD

**Issue by yura11212** [vertexofvortex/minecorpmod#5]
Вообщем я когда выбираю скругление то как-бы кнопки не хотят менять свой вид потому-что кто-то это явно не настроил (Жаль тут нет смайликов)

Вообщем предлагаю добавить отдельный ползунок на скругление кнопок (Глупо?) Ну или сделать привязку кнопок к скруглению.

![FhTlUnlN0Z](https://user-images.githubusercontent.com/60667108/73778450-eb336500-4793-11ea-98f4-7caaec766d1d.gif)

**Comment by vertexofvortex** [comment]
Изменение закругления кнопок не было предусмотрено.
